#ifndef TESTPLUGIN_GLOBAL_HPP
#define TESTPLUGIN_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(SKYWARDSWORDPLUGGIN_LIBRARY)
#  define SKYWARDSWORDPLUGGIN_EXPORT Q_DECL_EXPORT
#else
#  define SKYWARDSWORDPLUGGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTPLUGIN_GLOBAL_HPP
