#ifndef OOTSAVEPLUGIN_GLOBAL_HPP
#define OOTSAVEPLUGIN_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(OOTSAVEPLUGIN_LIBRARY)
#  define OOTSAVEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OOTSAVEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OOTSAVEPLUGIN_GLOBAL_HPP
